name: Build & Release Swift Packages

on:
  push:
    tags:
      - 'v*'       # v1.2.3, v0.0.1
      - '[0-9]*'   # 1.2.3, 0.0.1

jobs:
  build-release:
    runs-on: ubuntu-latest

    env:
      NAME: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version from Git tag
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Install Swift and packaging tools
        run: |
          sudo apt update
          sudo apt install -y rpm dpkg-dev curl git clang libcurl4-openssl-dev libssl-dev libatomic1
          curl -O https://download.swift.org/swift-5.9-release/ubuntu2204/swift-5.9-RELEASE/swift-5.9-RELEASE-ubuntu22.04.tar.gz
          tar -xzf swift-5.9-RELEASE-ubuntu22.04.tar.gz
          echo "$(pwd)/swift-5.9-RELEASE-ubuntu22.04/usr/bin" >> $GITHUB_PATH
          chmod +x scripts/*.sh

      - name: Build RPM
        run: ./scripts/build-rpm.sh $NAME $VERSION

      - name: Build DEB
        run: ./scripts/build-deb.sh $NAME $VERSION

      - name: Collect packages
        run: |
          mkdir release
          cp ~/rpmbuild/RPMS/**/*.rpm release/ || echo "No RPM found"
          cp build-deb/*.deb release/ || echo "No DEB found"

      - name: Upload packages to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: "Release ${{ steps.version.outputs.version }}"
          tag_name: ${{ github.ref }}
          files: |
            release/*.rpm
            release/*.deb
          overwrite: true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}