name: Build & Publish Swift Packages

on:
  push:
    tags:
      - 'v*'
      - '[0-9]*'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    container:
      image: swift:6.0 
    permissions:
      contents: write

    env:
      NAME: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version from tag
        id: extract
        run: |
          VERSION="${GITHUB_REF#refs/tags/}"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Install packaging tools
        run: |
          apt-get update
          apt-get install -y rpm dpkg-dev curl git clang libcurl4-openssl-dev libssl-dev libatomic1
          chmod +x scripts/*.sh

      - name: Build RPM
        run: ./scripts/build-rpm.sh $NAME $VERSION

      - name: Build DEB
        run: ./scripts/build-deb.sh $NAME $VERSION

      - name: Collect packages
        run: |
          mkdir release
          cp ~/rpmbuild/RPMS/**/*.rpm release/
          cp build-deb/*.deb release/

      - name: Collect and verify packages
        run: |
          mkdir -p release
          cp ~/rpmbuild/RPMS/**/*.rpm release/ || echo "No RPMs found"
          cp build-deb/*.deb release/ || echo "No DEBs found"
          echo "Contents of release dir:"
          ls -lh release

      - name: Upload assets to release
        uses: AButler/upload-release-assets@v3.0
        with:
          files: release/*.rpm;release/*.deb
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: ${{ github.ref_name }}

  build-macos:
    runs-on: macos-latest
    needs: build-linux
    permissions:
      contents: write

    env:
      NAME: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version from tag
        id: extract
        run: |
          VERSION="${GITHUB_REF#refs/tags/}"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Install Swift 6.0
        run: |
          curl -L https://download.swift.org/swift-6.0-release/xcode/swift-6.0-RELEASE/swift-6.0-RELEASE-osx.pkg -o swift.pkg
          sudo installer -pkg swift.pkg -target /
          export PATH="/Library/Developer/Toolchains/swift-6.0-RELEASE.xctoolchain/usr/bin:$PATH"
          swift --version
    
      - name: Build binary with Swift 6.0
        run: |
          export PATH="/Library/Developer/Toolchains/swift-6.0-RELEASE.xctoolchain/usr/bin:$PATH"
          swift build -c release
          mkdir -p pkg-root/usr/local/bin
          cp .build/release/$NAME pkg-root/usr/local/bin/

      - name: Create .pkg installer
        run: |
          pkgbuild \
            --identifier com.example.$NAME \
            --version "$VERSION" \
            --install-location /usr/local/bin \
            --root pkg-root \
            "$NAME-$VERSION.pkg"
          echo "Created package: $NAME-$VERSION.pkg"

      - name: Upload .pkg to release
        uses: AButler/upload-release-assets@v3.0
        with:
          files: *.pkg
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: ${{ github.ref_name }}